### ISSUE TITLE
Training code and dataset?

### ISSUE THREAD

**Issue by Jerrypiglet** [DiffusionLight/DiffusionLight#15]
Hi there, great work! May I ask if there is a plan to release the training code and the generated synthetic dataset? As far as I can see, the training part is the fine-tuning of the Stable Diffusion model with LoRA (Fig. 3 -> (b)) Thanks!

**Comment by pureexe** [comment]
I uploaded the training code for the LoRA at this repo.

https://github.com/DiffusionLight/DiffusionLight-LoRA-Trainer

For the generated synthetic dataset, It will be on [OneDrive (133 GB)](https://vistec-my.sharepoint.com/:f:/g/personal/pakkapon_p_s19_vistec_ac_th/Es_xIFk67UBPkVdW25cwDScBdvNlsZYz8lZblO7ZGzqGNg?e=q1dUqd). However, the datasets is so large, i'm still uploading. Please comeback and check the files in next 12 hours.

**Comment by ohhyonghee** [comment]
Thank you for releasing your code.
