### ISSUE TITLE
Collab error on Inpainting Chromeball cell

### ISSUE THREAD

**Issue by jbkrauss** [DiffusionLight/DiffusionLight#19]
Hey everyone, than you for this amazing resource !

I was trying to use the colab earlier, and everytime I tried it would fail on this line of this cell :
` pred_images.append(np.asarray(Image.open("output/raw/image_ev"+ev_str+".png").resize((512,512))))`

I'm quite new to colab, so I had a look at the files tab on the left, and sure enough, there were no files in the output/raw folder.

Am I doing something wrong? Or is the colab broken?
Thank you !

**Comment by pureexe** [comment]
I tested on Collab, and it doesn't have any errors. 

Does it have an error on the previous block? 

from the error message, it seems to have an error from the previous block. because it cannot run `Image.open`.
