### ISSUE TITLE
it seems don't work without huggingface connecting.

### ISSUE THREAD

**Issue by antimattergroup** [DiffusionLight/DiffusionLight#20]
So I find this in my console:
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

OSError: madebyollin/sdxl-vae-fp16-fix does not appear to have a file named config.json

**Comment by pureexe** [comment]
We use huggingface's diffusers and it will download additional model after the code is execute. 

Here is the solution.
1. Make sure that the internet is working. Including checking all firewalls and make sure that you are able to download this file "https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/config.json?download=true"

2. You may use [HuggingFace offline mode](https://huggingface.co/docs/transformers/v4.15.0/en/installation#offline-mode) in case you are in strict environment that cannot connect to public internet

**Comment by antimattergroup** [comment]
> 我们使用huggingface的扩散器，它会在代码执行后下载额外的模型。
> 
> 这是解决方案。
> 
> 1. 确保互联网正常工作。包括检查所有防火墙并确保您能够下载此文件“ https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/config.json?download=true ”
> 2. 如果您处于无法连接公共互联网的严格环境中，您可以使用[HuggingFace离线模式](https://huggingface.co/docs/transformers/v4.15.0/en/installation#offline-mode)

thx, so I tried to downloading model and load them in my local path, it works.
